### ISSUE TITLE
Increasing the pill size

### ISSUE THREAD

**Issue by avrabyt** [jrieke/streamlit-pills#6]
Also , was wondering, if it would possible to control the pills sizes ? 🤔

**Comment by jrieke** [comment]
Streamlit has pills as a built-in feature now, using st.pills. See [docs](https://docs.streamlit.io/develop/api-reference/widgets/st.pills). Please use that instead of this component! We are not planning to add an option for pill sizes specifically but will soon ship advanced theming, which will let you set the sizes of all elements.
